class_notes_task:
  description: >
    Extract and organize detailed class notes from the course syllabus. 
    Identify key topics, concepts, and definitions, ensuring clarity and coherence. 
    The output should be in the same language as the course syllabus
    This is the course syllabus: 
    {course_plan}
  expected_output: >
    A structured document with comprehensive class notes, including explanations, 
    examples, and key takeaways for each section of the syllabus, written in the 
    same language as the course syllabus.
  agent: scholar

learning_objectives_task:
  description: >
    Identify and formulate clear learning objectives for each topic found in the 
    course syllabus. These objectives should describe what students 
    should achieve after studying the material. 
    The output should be in the same language as the course syllabus.
    This is the course syllabus: 
    {course_plan}
  expected_output: >
    A list of well-defined learning objectives for each major section of the syllabus, 
    written in the same language as the course syllabus.
  agent: scholar