discussion_questions_task:
  description: >
    Analyze the course syllabus and develop thought-provoking discussion 
    questions that encourage critical thinking and debate. 
    The output should be in the same language as the course syllabus.
    This is the course syllabus: 
    {course_plan}
  expected_output: >
    A list of 5-8 discussion questions designed to spark meaningful conversations, 
    written in the same language as the course syllabus.
  agent: debater